### ISSUE TITLE
Check whether unistd.h issue was fixed

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#62] opened 2015-01-13 20:41 UTC

**Comment by rplzzz** [comment] 2015-01-28 20:21
The `unistd.h` problem appears to have been fixed by commenting out the include in `logger.hpp`.  This include appears to have been unnecessary anyhow (I probably had originally planned to define the functions that needed it inline and changed my mind).  Therefore, I have removed the include entirely.  The one in `logger.cpp` is still being used, and since there have been no complaints from windows users, I presume that the guards around the include are working as intended.  If that's not the case, then please let me know.

**Closed by rplzzz** 2015-01-28 20:21 UTC
