### ISSUE TITLE
Ocean components outputs in basic run

### ISSUE THREAD

**Issue by jmemb** [JGCRI/hector#436] opened 2021-04-26 14:18 UTC
When following the instruction of a [basic run](https://jgcri.github.io/hector/articles/intro-to-hector.html) with original INI files and trying to obtain PH_LL() or PH_LL (test <- fetchvars(core, 2005:2100, PH_HL())), there is the error "Unknown model datum: PH_HL". There is no error when retrieving most of the other outputs, but the only ocean component output which can be obtained is OCEAN_CFLUX().

**Comment by kdorheim** [comment] 2021-04-27 01:09
Hi @jmemb thanks for opening this issue! I _think_ I know the cause of this problem but will need about a week to look into it. 👍

**Comment by jmemb** [comment] 2021-04-27 08:00
Sounds great! Thanks a lot @kdorheim

**Comment by kdorheim** [comment] 2021-05-03 13:22
@jmemb I just wanted to check in about this issue, while it is not 100% resolved we are working on it. You can follow our progress with PR #439.

**Comment by bpbond** [comment] 2021-05-06 14:59
Resolved by #439

**Closed by bpbond** 2021-05-06 14:59 UTC

**Comment by kdorheim** [comment] 2021-05-06 15:12
@jmemb  this issue has been resolved and merged into the master branch. If you reinstall Hector run `remotes::install_github('jgcri/hector')` you should be able to access the ocean variables now. 👍

**Comment by jmemb** [comment] 2021-05-07 16:39
Yes! It works now, thank you very much @kdorheim!

**Comment by bpbond** [comment] 2021-05-07 19:49
👏 👏 👏
