### ISSUE TITLE
Wiki documentation versioning

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#130] opened 2016-01-12 15:56 UTC
how to link to releases?

**Comment by rplzzz** [comment] 2016-01-12 18:58
The only solution I have been able to come up with for this is to make the old releases subtrees within the wiki repository.  Then the main page becomes a brief introduction to Hector with a list of links to a main page within the subtree for each release.

It's kind of ugly, and we may have to play with it a bit to get the internal links to work consistently, but I think it will work.

**Comment by rgieseke** [comment] 2016-01-25 10:46
Not sure if that would solve the original question but have you considered moving the wiki documentation directly into the main repo?

The markdown rendering and online editing is probably good enough and that way the documentation would more easily stay in sync with the code (and could simply be reproduced when checking out different states of the repo). At the moment the subtree is outdated I think.

It's also possible to have relative links to other files: https://help.github.com/articles/relative-links-in-readmes/

**Comment by rplzzz** [comment] 2016-01-26 19:24
The wiki does have some nice features (like the sidebar) that we lose if we go to simple markdown files versioned in the repository, but at this point it seems like that's going to be the only way to keep documentation synced to the code.

The wiki subrepository is almost certainly out of date, since subrepositories have to have the commit that they point to in their host repository updated manually, and I don't think anybody has done this.

**Comment by cahartin** [comment] 2019-04-08 19:52
@ashiklom can we close this issue with your recent PR?

**Comment by ashiklom** [comment] 2019-04-09 16:12
Once that PR is merged, yeah. I think @bpbond wanted that to get another review before it was merged.

**Closed** 2019-04-11 13:57 UTC
Labels: documentation
